import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { useTranslation } from "react-i18next";
import { useNavigate, useLocation } from "react-router-dom";
import { toast } from "react-hot-toast";
import {
  ArrowLeft,
  ArrowRight,
  User,
  Phone,
  MapPin,
  Receipt,
  Truck,
  Store,
  CreditCard,
  Wallet,
  Banknote,
  Calendar,
  Printer,
  RotateCcw,
} from "lucide-react";
import FormField from "../../../components/Forms/FormField";
import { createOrder } from "../../../store/slices/ordersSlice";
import { createCustomer } from "../../../store/slices/customerSlice";

const CheckoutPage = () => {
  const { t } = useTranslation();
  const { isRTL } = useSelector((state) => state.language);
  const navigate = useNavigate();
  const location = useLocation();
  const dispatch = useDispatch();

  const orderData = location.state?.orderData;

  const [deliveryType, setDeliveryType] = useState("pickup");
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [customerInfo, setCustomerInfo] = useState({
    name: "",
    phone: "",
    address: "",
  });
  const [errors, setErrors] = useState({});

  // Credit payment state
  const [existingCustomers, setExistingCustomers] = useState([]);
  const [selectedCustomerId, setSelectedCustomerId] = useState("");
  const [isNewCustomer, setIsNewCustomer] = useState(true);

  // Discount state
  const [discountType, setDiscountType] = useState("none"); // none | code | percent
  const [discountCode, setDiscountCode] = useState("");
  const [discountPercent, setDiscountPercent] = useState("");

  // Simple mock discount codes (placeholder until backend/API)
  const DISCOUNT_CODES = {
    SAVE10: { kind: "percent", value: 10 },
    OFF20: { kind: "percent", value: 20 },
    FLAT5: { kind: "amount", value: 5 },
  };

  const subtotal = orderData.total || 0;

  const getDiscountValue = () => {
    if (!subtotal || subtotal <= 0) return 0;
    if (discountType === "percent") {
      const percent = Math.max(
        0,
        Math.min(100, parseFloat(discountPercent) || 0)
      );
      return (subtotal * percent) / 100;
    }
    if (discountType === "code") {
      const code = discountCode.trim().toUpperCase();
      const rule = DISCOUNT_CODES[code];
      if (!rule) return 0;
      if (rule.kind === "percent") {
        return (subtotal * rule.value) / 100;
      }
      if (rule.kind === "amount") {
        return Math.min(subtotal, rule.value);
      }
    }
    return 0;
  };

  const discountValue = Math.min(subtotal, getDiscountValue());
  const grandTotal = Math.max(0, subtotal - discountValue);

  useEffect(() => {
    if (!orderData) {
      navigate("/seller/products");
      toast.error(t("noOrderDataFound"));
    }
  }, [orderData, navigate, t]);

  useEffect(() => {
    // Load existing customers when credit payment is selected
    if (paymentMethod === "credit") {
      // For now, use empty array - customers will be loaded from Redux
      setExistingCustomers([]);
    }
  }, [paymentMethod]);

  if (!orderData) {
    return null;
  }

  const validateForm = () => {
    const newErrors = {};

    // Validate delivery customer info
    if (deliveryType === "delivery") {
      if (!customerInfo.name.trim()) {
        newErrors.name = t("customerNameRequired");
      }
      if (!customerInfo.phone.trim()) {
        newErrors.phone = t("phoneRequired");
      }
      if (!customerInfo.address.trim()) {
        newErrors.address = t("addressRequired");
      }
    }

    // Validate credit payment customer info
    if (paymentMethod === "credit") {
      if (isNewCustomer) {
        if (!customerInfo.name.trim()) {
          newErrors.name = t("customerNameRequired");
        }
        if (!customerInfo.phone.trim()) {
          newErrors.phone = t("phoneRequired");
        }
      } else {
        if (!selectedCustomerId) {
          newErrors.customer = t("pleaseSelectCustomer");
        }
      }
    }

    if (!paymentMethod) {
      newErrors.paymentMethod = t("paymentMethodRequired");
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = () => {
    if (!validateForm()) {
      return;
    }

    // Order ID will be generated by the backend

    // Get customer info based on selection
    let finalCustomerInfo = { ...customerInfo };
    if (paymentMethod === "credit" && !isNewCustomer && selectedCustomerId) {
      const selectedCustomer = existingCustomers.find(
        (c) => c.id === selectedCustomerId
      );
      if (selectedCustomer) {
        finalCustomerInfo = {
          name: selectedCustomer.name,
          phone: selectedCustomer.phone,
          address: selectedCustomer.address || "",
        };
      }
    }

    // Save new customer if credit payment and new customer
    if (
      paymentMethod === "credit" &&
      isNewCustomer &&
      customerInfo.name.trim()
    ) {
      const newCustomer = {
        name: customerInfo.name.trim(),
        phone: customerInfo.phone.trim(),
        address: customerInfo.address?.trim() || "",
      };

      // Create customer via Redux
      dispatch(createCustomer(newCustomer));
      setExistingCustomers([...existingCustomers, newCustomer]);
    }

    const finalOrderData = {
      ...orderData,
      deliveryType,
      paymentMethod,
      customer: finalCustomerInfo.name,
      phone: finalCustomerInfo.phone,
      deliveryAddress: finalCustomerInfo.address,
      status: "pending",
    };

    // Add order to Redux store
    dispatch(createOrder(finalOrderData));

    // Payment will be handled by the backend API
    // addPayment(paymentData);

    navigate("/seller/orders", {
      state: {
        newOrder: finalOrderData,
        showSuccessMessage: true,
      },
    });

    toast.success(t("orderCreatedSuccessfully"));
  };

  const handleBackToProducts = () => {
    navigate("/seller", { state: { orderData } });
  };

  const handlePrintOrder = () => {
    const printContent = `
=================================
          طلب / ORDER
=================================

رقم الطلب / Order ID: ${Date.now()}
التاريخ / Date: ${new Date().toLocaleDateString()}
الوقت / Time: ${new Date().toLocaleTimeString()}

---------------------------------
تفاصيل الطلب / Order Details:
${orderData.products
  .map(
    (product, index) => `
${index + 1}. ${isRTL ? product.name : product.nameEn}
   الكمية / Quantity: ${product.quantity}
   السعر / Price: ${product.price} ${t("sar")}
   الإجمالي / Subtotal: ${(product.price * product.quantity).toFixed(2)} ${t(
      "sar"
    )}
`
  )
  .join("")}

---------------------------------
طريقة التوصيل / Delivery Type: ${t(deliveryType)}
طريقة الدفع / Payment Method: ${t(paymentMethod)}

${
  deliveryType === "delivery"
    ? `
معلومات العميل / Customer Information:
الاسم / Name: ${customerInfo.name}
الهاتف / Phone: ${customerInfo.phone}
العنوان / Address: ${customerInfo.address}
`
    : ""
}

---------------------------------
الإجمالي قبل الخصم / Subtotal: ${subtotal.toFixed(2)} ${t("sar")}
$${
      discountValue > 0
        ? `\nالخصم / Discount: -${discountValue.toFixed(2)} ${t("sar")}`
        : ""
    }
\nالإجمالي بعد الخصم / Total: ${grandTotal.toFixed(2)} ${t("sar")}

=================================
شكراً لك / Thank You!
=================================
    `;

    const printWindow = window.open("", "_blank");
    printWindow.document.write(`
      <html>
        <head>
          <title>${t("order")} - ${new Date().toLocaleDateString()}</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              margin: 20px; 
              line-height: 1.6;
            }
            .header { 
              text-align: center; 
              margin-bottom: 20px; 
              font-weight: bold;
              font-size: 18px;
            }
            .section { 
              margin: 15px 0; 
            }
            .total { 
              font-weight: bold; 
              font-size: 18px; 
              border-top: 2px solid #000;
              padding-top: 10px;
            }
            @media print {
              body { margin: 0; }
            }
          </style>
        </head>
        <body>
          <pre style="font-family: 'Courier New', monospace; white-space: pre-wrap;">${printContent}</pre>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleResetForm = () => {
    setDeliveryType("pickup");
    setPaymentMethod("cash");
    setCustomerInfo({
      name: "",
      phone: "",
      address: "",
    });
    setSelectedCustomerId("");
    setIsNewCustomer(true);
    setDiscountType("none");
    setDiscountCode("");
    setDiscountPercent("");
    setErrors({});
    toast.success(t("formResetSuccessfully"));
  };

  const handleCustomerSelection = (customerId) => {
    setSelectedCustomerId(customerId);
    if (customerId) {
      const selectedCustomer = existingCustomers.find(
        (c) => c.id === customerId
      );
      if (selectedCustomer) {
        setCustomerInfo({
          name: selectedCustomer.name,
          phone: selectedCustomer.phone,
          address: selectedCustomer.address || "",
        });
      }
    } else {
      setCustomerInfo({
        name: "",
        phone: "",
        address: "",
      });
    }
  };

  const paymentMethods = [
    {
      id: "cash",
      label: t("cash"),
      icon: Banknote,
      description: t("payWithCash"),
    },
    {
      id: "card",
      label: t("card"),
      icon: CreditCard,
      description: t("payWithCard"),
    },
    {
      id: "knet",
      label: t("knet"),
      icon: Wallet,
      description: t("payWithKNET"),
    },
    {
      id: "credit",
      label: t("credit"),
      icon: Calendar,
      description: t("payWithCredit"),
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={handleBackToProducts}
            className={`inline-flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors mb-4 ${
              isRTL ? "flex-row" : ""
            }`}
          >
            {isRTL ? (
              <ArrowRight className="w-4 h-4" />
            ) : (
              <ArrowLeft className="w-4 h-4" />
            )}
            {t("backToProducts")}
          </button>

          <h1
            className={`text-2xl font-bold text-gray-900 dark:text-white mb-2`}
          >
            {t("checkout")}
          </h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
          {/* Order Summary */}
          <div className="lg:col-span-1">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg dark:shadow-xl border border-gray-200 dark:border-gray-700 p-6 lg:sticky lg:top-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
                  {t("orderSummary")}
                </h2>
                <div className="flex gap-2">
                  <button
                    onClick={handlePrintOrder}
                    className="p-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    title={t("printOrder")}
                    aria-label={t("printOrder")}
                  >
                    <Printer className="w-4 h-4" />
                  </button>
                  <button
                    onClick={handleResetForm}
                    className="p-2 text-text-secondary-light dark:text-text-secondary-dark hover:text-text-primary-light dark:hover:text-text-primary-dark hover:bg-surface-light dark:hover:bg-surface-dark rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    title={t("resetForm")}
                    aria-label={t("resetForm")}
                  >
                    <RotateCcw className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Products List */}
              <div className="space-y-4 mb-6 max-h-64 sm:max-h-80 overflow-y-auto pr-1">
                {orderData.products.map((product, index) => (
                  <div
                    key={index}
                    className={`flex justify-between items-center p-3 bg-gray-50 dark:bg-gray-700 rounded-lg ${
                      isRTL ? "flex-row" : ""
                    }`}
                  >
                    <div>
                      <p className="font-medium text-gray-900 dark:text-white">
                        {isRTL ? product.name : product.nameEn}
                      </p>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        {t("quantity")}: {product.quantity}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="font-medium text-gray-900 dark:text-white">
                        {(product.price * product.quantity).toFixed(2)}{" "}
                        {t("sar")}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Discount Controls */}
              <div className="mb-4 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
                <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-200">
                    {t("discount")}
                  </span>
                  <div className="flex gap-2 flex-wrap">
                    <button
                      onClick={() => {
                        setDiscountType("none");
                        setDiscountCode("");
                        setDiscountPercent("");
                      }}
                      className={`px-2 py-1 rounded text-xs border transition-colors ${
                        discountType === "none"
                          ? "bg-blue-600 text-white border-blue-600"
                          : "bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600"
                      }`}
                    >
                      {t("none")}
                    </button>
                    <button
                      onClick={() => {
                        setDiscountType("code");
                        setDiscountPercent("");
                      }}
                      className={`px-2 py-1 rounded text-xs border transition-colors ${
                        discountType === "code"
                          ? "bg-blue-600 text-white border-blue-600"
                          : "bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600"
                      }`}
                    >
                      {t("code")}
                    </button>
                    <button
                      onClick={() => {
                        setDiscountType("percent");
                        setDiscountCode("");
                      }}
                      className={`px-2 py-1 rounded text-xs border transition-colors ${
                        discountType === "percent"
                          ? "bg-blue-600 text-white border-blue-600"
                          : "bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600"
                      }`}
                    >
                      {t("percent")}
                    </button>
                  </div>
                </div>

                {discountType === "code" && (
                  <div className="flex items-center gap-2 flex-wrap">
                    <input
                      type="text"
                      value={discountCode}
                      onChange={(e) => setDiscountCode(e.target.value)}
                      placeholder={t("enterDiscountCode")}
                      className="flex-1 min-w-[200px] px-3 py-2 rounded border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <span className="text-xs text-gray-500 dark:text-gray-400">
                      SAVE10, OFF20, FLAT5
                    </span>
                  </div>
                )}

                {discountType === "percent" && (
                  <div className="flex items-center gap-2 flex-wrap">
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={discountPercent}
                      onChange={(e) => setDiscountPercent(e.target.value)}
                      placeholder={t("enterPercentage")}
                      className="flex-1 min-w-[140px] px-3 py-2 rounded border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <span className="text-sm text-gray-700 dark:text-gray-300">
                      %
                    </span>
                  </div>
                )}
              </div>

              {/* Totals */}
              <div className="border-t border-gray-200 dark:border-gray-700 pt-4">
                <div
                  className={`flex justify-between items-center mb-2 ${
                    isRTL ? "flex-row" : ""
                  }`}
                >
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                    {t("subtotal")}
                  </span>
                  <span className="text-sm font-semibold text-gray-900 dark:text-white">
                    {subtotal.toFixed(2)} {t("currency")}
                  </span>
                </div>
                {discountValue > 0 && (
                  <div
                    className={`flex justify-between items-center mb-2 ${
                      isRTL ? "flex-row" : ""
                    }`}
                  >
                    <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                      {t("discount")}
                    </span>
                    <span className="text-sm font-semibold text-green-600 dark:text-green-400">
                      -{discountValue.toFixed(2)} {t("sar")}
                    </span>
                  </div>
                )}
                <div
                  className={`flex justify-between items-center ${
                    isRTL ? "flex-row" : ""
                  }`}
                >
                  <span className="text-lg font-semibold text-gray-900 dark:text-white">
                    {t("total")}
                  </span>
                  <span className="text-lg font-bold text-gray-900 dark:text-white">
                    {grandTotal.toFixed(2)} {t("sar")}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Delivery Options and Customer Info */}
          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg dark:shadow-xl border border-gray-200 dark:border-gray-700 p-6">
              {/* Delivery Type Selection */}
              <div className="mb-8">
                <h3
                  className={`text-lg font-semibold text-gray-900 dark:text-white mb-4`}
                >
                  {t("deliveryOption")}
                </h3>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <button
                    onClick={() => setDeliveryType("pickup")}
                    className={`p-4 rounded-xl border-2 transition-all duration-300 w-full ${
                      deliveryType === "pickup"
                        ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                        : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-300 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/10 hover:shadow-md"
                    }`}
                    aria-pressed={deliveryType === "pickup"}
                    aria-label={t("pickup")}
                  >
                    <div className="flex items-center gap-3">
                      <Store
                        className={`w-6 h-6 ${
                          deliveryType === "pickup"
                            ? "text-blue-600 dark:text-blue-400"
                            : "text-gray-600 dark:text-gray-400"
                        }`}
                      />
                      <div className="flex flex-col items-start">
                        <p
                          className={`font-medium ${
                            deliveryType === "pickup"
                              ? "text-blue-700 dark:text-blue-300"
                              : "text-gray-900 dark:text-white"
                          }`}
                        >
                          {t("pickup")}
                        </p>
                        <p
                          className={`text-sm ${
                            deliveryType === "pickup"
                              ? "text-blue-600 dark:text-blue-400"
                              : "text-gray-600 dark:text-gray-400"
                          }`}
                        >
                          {t("pickupDescription")}
                        </p>
                      </div>
                    </div>
                  </button>

                  <button
                    onClick={() => setDeliveryType("delivery")}
                    className={`p-4 rounded-xl border-2 transition-all duration-300 w-full ${
                      deliveryType === "delivery"
                        ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                        : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-300 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/10 hover:shadow-md"
                    }`}
                    aria-pressed={deliveryType === "delivery"}
                    aria-label={t("delivery")}
                  >
                    <div className="flex items-center gap-3">
                      <Truck
                        className={`w-6 h-6 ${
                          deliveryType === "delivery"
                            ? "text-blue-600 dark:text-blue-400"
                            : "text-gray-600 dark:text-gray-400"
                        }`}
                      />
                      <div className="flex flex-col items-start">
                        <p
                          className={`font-medium ${
                            deliveryType === "delivery"
                              ? "text-blue-700 dark:text-blue-300"
                              : "text-gray-900 dark:text-white"
                          }`}
                        >
                          {t("delivery")}
                        </p>
                        <p
                          className={`text-sm ${
                            deliveryType === "delivery"
                              ? "text-blue-600 dark:text-blue-400"
                              : "text-gray-600 dark:text-gray-400"
                          }`}
                        >
                          {t("deliveryDescription")}
                        </p>
                      </div>
                    </div>
                  </button>
                </div>
              </div>

              {/* Payment Method Selection */}
              <div className="mb-8">
                <h3
                  className={`text-lg font-semibold text-gray-900 dark:text-white mb-4`}
                >
                  {t("paymentMethod")}
                </h3>

                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  {paymentMethods.map((method) => (
                    <button
                      key={method.id}
                      onClick={() => setPaymentMethod(method.id)}
                      className={`p-4 rounded-xl border-2 transition-all duration-300 w-full ${
                        paymentMethod === method.id
                          ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                          : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-300 dark:hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/10 hover:shadow-md"
                      }`}
                      aria-pressed={paymentMethod === method.id}
                      aria-label={method.label}
                    >
                      <div className="flex flex-col items-center gap-2 text-center">
                        <method.icon
                          className={`w-6 h-6 ${
                            paymentMethod === method.id
                              ? "text-blue-600 dark:text-blue-400"
                              : "text-gray-600 dark:text-gray-400"
                          }`}
                        />
                        <div>
                          <p
                            className={`font-medium ${
                              paymentMethod === method.id
                                ? "text-blue-700 dark:text-blue-300"
                                : "text-gray-900 dark:text-white"
                            }`}
                          >
                            {method.label}
                          </p>
                          <p
                            className={`text-sm ${
                              paymentMethod === method.id
                                ? "text-blue-600 dark:text-blue-400"
                                : "text-gray-600 dark:text-gray-400"
                            }`}
                          >
                            {method.description}
                          </p>
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
                {errors.paymentMethod && (
                  <p className="mt-2 text-sm text-red-600 dark:text-red-400">
                    {errors.paymentMethod}
                  </p>
                )}
              </div>

              {/* Customer Information Form for Delivery */}
              {deliveryType === "delivery" && paymentMethod !== "credit" && (
                <div className="space-y-6">
                  <h3
                    className={`text-lg font-semibold text-gray-900 dark:text-white mb-4`}
                  >
                    {t("customerInformation")}
                  </h3>

                  <FormField
                    label={t("customerName")}
                    value={customerInfo.name}
                    onChange={(e) =>
                      setCustomerInfo((prev) => ({
                        ...prev,
                        name: e.target.value,
                      }))
                    }
                    error={errors.name}
                    icon={<User className="w-4 h-4" />}
                  />

                  <FormField
                    label={t("phoneNumber")}
                    value={customerInfo.phone}
                    onChange={(e) =>
                      setCustomerInfo((prev) => ({
                        ...prev,
                        phone: e.target.value,
                      }))
                    }
                    error={errors.phone}
                    icon={<Phone className="w-4 h-4" />}
                  />

                  <FormField
                    label={t("deliveryAddress")}
                    value={customerInfo.address}
                    onChange={(e) =>
                      setCustomerInfo((prev) => ({
                        ...prev,
                        address: e.target.value,
                      }))
                    }
                    error={errors.address}
                    icon={<MapPin className="w-4 h-4" />}
                  />
                </div>
              )}

              {/* Credit Payment Customer Form */}
              {paymentMethod === "credit" && (
                <div className="space-y-6">
                  <h3
                    className={`text-lg font-semibold text-gray-900 dark:text-white mb-4`}
                  >
                    {t("customerInformation")}
                  </h3>

                  {/* Customer Selection Toggle */}
                  <div className="flex gap-4 mb-6">
                    <button
                      type="button"
                      onClick={() => {
                        setIsNewCustomer(true);
                        setSelectedCustomerId("");
                        setCustomerInfo({ name: "", phone: "", address: "" });
                      }}
                      className={`px-4 py-2 rounded-lg border-2 transition-all duration-300 flex-1 ${
                        isNewCustomer
                          ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                          : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-300 dark:hover:border-blue-500"
                      }`}
                    >
                      {t("newCustomer")}
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        setIsNewCustomer(false);
                        setCustomerInfo({ name: "", phone: "", address: "" });
                      }}
                      className={`px-4 py-2 rounded-lg border-2 transition-all duration-300 flex-1 ${
                        !isNewCustomer
                          ? "border-blue-500 dark:border-blue-400 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300"
                          : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-300 dark:hover:border-blue-500"
                      }`}
                    >
                      {t("existingCustomer")}
                    </button>
                  </div>

                  {/* Existing Customer Dropdown */}
                  {!isNewCustomer && (
                    <div className="space-y-4">
                      <FormField
                        label={t("selectCustomer")}
                        type="select"
                        value={selectedCustomerId}
                        onChange={(e) =>
                          handleCustomerSelection(e.target.value)
                        }
                        error={errors.customer}
                        options={[
                          { value: "", label: t("selectCustomer") },
                          ...existingCustomers.map((customer) => ({
                            value: customer.id,
                            label: `${customer.name} - ${customer.phone}`,
                          })),
                        ]}
                      />

                      {selectedCustomerId && (
                        <div className="p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
                          <h4 className="text-sm font-medium text-gray-900 dark:text-white mb-2">
                            {t("selectedCustomerInfo")}
                          </h4>
                          <p className="text-sm text-gray-600 dark:text-gray-400">
                            <strong>{t("name")}:</strong> {customerInfo.name}
                          </p>
                          <p className="text-sm text-gray-600 dark:text-gray-400">
                            <strong>{t("phone")}:</strong> {customerInfo.phone}
                          </p>
                        </div>
                      )}
                    </div>
                  )}

                  {/* New Customer Form */}
                  {isNewCustomer && (
                    <div className="space-y-4">
                      <FormField
                        label={t("customerName")}
                        value={customerInfo.name}
                        onChange={(e) =>
                          setCustomerInfo((prev) => ({
                            ...prev,
                            name: e.target.value,
                          }))
                        }
                        error={errors.name}
                        icon={<User className="w-4 h-4" />}
                      />

                      <FormField
                        label={t("phoneNumber")}
                        value={customerInfo.phone}
                        onChange={(e) =>
                          setCustomerInfo((prev) => ({
                            ...prev,
                            phone: e.target.value,
                          }))
                        }
                        error={errors.phone}
                        icon={<Phone className="w-4 h-4" />}
                      />
                    </div>
                  )}

                  {/* Delivery Address for Credit + Delivery */}
                  {deliveryType === "delivery" && (
                    <FormField
                      label={t("deliveryAddress")}
                      value={customerInfo.address}
                      onChange={(e) =>
                        setCustomerInfo((prev) => ({
                          ...prev,
                          address: e.target.value,
                        }))
                      }
                      error={errors.address}
                      icon={<MapPin className="w-4 h-4" />}
                    />
                  )}
                </div>
              )}

              {/* Submit Button */}
              <button
                onClick={handleSubmit}
                className="w-full mt-8 px-6 py-3 bg-gray-900 dark:bg-gray-100 hover:bg-gray-800 dark:hover:bg-gray-200 text-white dark:text-gray-900 font-medium rounded-lg transition-all duration-300 flex items-center justify-center gap-2"
              >
                <Receipt className="w-5 h-5" />
                {t("placeOrder")}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CheckoutPage;
